CREATE SEQUENCE COUNTRY_SEQ INCREMENT 1 START 1 NOCACHE CYCLE;

CREATE TABLE IF NOT EXISTS COUNTRY (
		  ID INTEGER NOT NULL PRIMARY KEY CONSTRAINT PK_COUNTRY,
		  NAME VARCHAR(255)
		  );

CREATE SEQUENCE USERSDATA_SEQ INCREMENT 1 START 1 NOCACHE CYCLE;

CREATE TABLE IF NOT EXISTS USERSDATA (
		  ID INTEGER NOT NULL PRIMARY KEY CONSTRAINT PK_USERSDATA,
		  ROWVERSION DATETIME YEAR TO FRACTION(3),
		  TEXTVALUE VARCHAR(255),
		  INTVALUE INTEGER,
		  DOUBLEVALUE DOUBLE PRECISION,
		  BOOLVALUE BOOLEAN,
		  DATEVALUE DATE
                  );